const plugin = require('tailwindcss/plugin');

const colors = {
  background: '#000000',
  foreground: '#ffffff',
  card: { DEFAULT: '#16161a', foreground: '#ffffff' },
  elevated: { DEFAULT: '#1c1c20', foreground: '#ffffff' },
  popover: { DEFAULT: '#1c1c20', foreground: '#ffffff' },
  primary: { DEFAULT: '#ffffff', foreground: '#000000' },
  secondary: { DEFAULT: '#1c1c20', foreground: '#ffffff' },
  muted: { DEFAULT: '#101013', foreground: '#8e8e93' },
  accent: { DEFAULT: '#1c1c20', foreground: '#ffffff' },
  brand: { DEFAULT: '#ffffff', foreground: '#000000' },
  destructive: { DEFAULT: '#ff453a', foreground: '#ffffff' },
  success: { DEFAULT: '#34c759', foreground: '#04140a' },
  warning: { DEFAULT: '#ff9f0a', foreground: '#160f00' },
  border: '#26262c',
  input: '#1c1c20',
  ring: '#ffffff',
  sidebar: {
    DEFAULT: '#000000',
    foreground: '#ffffff',
    primary: '#ffffff',
    'primary-foreground': '#000000',
    accent: '#1c1c20',
    'accent-foreground': '#ffffff',
    border: '#26262c',
    ring: '#ffffff',
  },
  cat: {
    coral: '#ff6b57',
    blue: '#0a84ff',
    purple: '#bf5af2',
    green: '#34c759',
    orange: '#ff9f0a',
    pink: '#ff2d92',
    cyan: '#40c8e0',
    yellow: '#ffd60a',
  },
  chart: {
    1: '#0a84ff',
    2: '#bf5af2',
    3: '#34c759',
    4: '#ff9f0a',
    5: '#ff2d92',
  },
  git: {
    added: '#34c759',
    'added-subtle': '#0f2a1c',
    removed: '#ff453a',
    'removed-subtle': '#2e1213',
    modified: '#ff9f0a',
    'modified-subtle': '#2a2200',
    branch: '#0a84ff',
    merge: '#bf5af2',
    tag: '#ff9f0a',
    hash: '#8e8e93',
  },
  agent: {
    claude: '#d97757',
    codex: '#f6f6f8',
    gemini: '#4d9fff',
    copilot: '#a06bff',
  },
};

module.exports = {
  darkMode: 'class',
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}', './lib/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors,
      fontFamily: {
        sans: ['Geist_400Regular'],
        mono: ['GeistMono_400Regular'],
      },
      borderRadius: {
        sm: '8px',
        DEFAULT: '12px',
        md: '14px',
        lg: '16px',
        xl: '20px',
        '2xl': '24px',
        '3xl': '30px',
      },
      fontSize: {
        '2xs': ['10px', '14px'],
        xs: ['11px', '16px'],
        sm: ['13px', '18px'],
        base: ['15px', '21px'],
        lg: ['17px', '24px'],
        xl: ['20px', '26px'],
        '2xl': ['24px', '30px'],
        '3xl': ['30px', '36px'],
        '4xl': ['36px', '40px'],
        '5xl': ['44px', '46px'],
      },
    },
  },
  plugins: [
    plugin(({ addUtilities }) => {
      addUtilities({
        '.font-sans': { fontFamily: 'Geist_400Regular' },
        '.font-normal': { fontFamily: 'Geist_400Regular' },
        '.font-medium': { fontFamily: 'Geist_500Medium' },
        '.font-semibold': { fontFamily: 'Geist_600SemiBold' },
        '.font-bold': { fontFamily: 'Geist_700Bold' },
        '.font-extrabold': { fontFamily: 'Geist_700Bold' },
        '.font-mono': { fontFamily: 'GeistMono_400Regular' },
        '.font-mono-medium': { fontFamily: 'GeistMono_500Medium' },
      });
    }),
  ],
};
