/**
 * Claude Code writes protocol scaffolding into the plain-text content of user
 * transcript entries: slash commands become `<command-name>` blocks, their
 * local output arrives as `<local-command-stdout>`, and the CLI injects
 * `<system-reminder>` / caveat blocks that were never meant for a reader.
 *
 * Rendering those blocks verbatim floods the chat with XML, so every place
 * that surfaces transcript text runs it through this parser first.
 */

/** Blocks that carry no reader-facing value and are dropped completely. */
const DROPPED_TAGS = [
  "system-reminder",
  "local-command-caveat",
  "command-message",
  "user-prompt-submit-hook",
  "ide_opened_file",
  "ide_selection",
  "ide_diagnostics",
] as const;

/** Blocks that hold the output of a locally executed command. */
const OUTPUT_TAGS = [
  "local-command-stdout",
  "local-command-stderr",
  "bash-stdout",
  "bash-stderr",
] as const;

/** Blocks that name the invoked command. */
const COMMAND_TAGS = ["command-name", "bash-input"] as const;

/** Blocks holding the arguments passed to the invoked command. */
const ARGUMENT_TAGS = ["command-args", "command-contents"] as const;

const ALL_TAGS = [...DROPPED_TAGS, ...OUTPUT_TAGS, ...COMMAND_TAGS, ...ARGUMENT_TAGS];

const TAG_PATTERN = new RegExp(`<(${ALL_TAGS.join("|")})>([\\s\\S]*?)<\\/\\1>`, "gi");
// Truncated transcripts can leave a dangling open tag; drop the remainder.
const DANGLING_PATTERN = new RegExp(`<(?:${ALL_TAGS.join("|")})>[\\s\\S]*$`, "i");
const ORPHAN_PATTERN = new RegExp(`<\\/?(?:${ALL_TAGS.join("|")})>`, "gi");
// Older CLI releases emitted the caveat as bare prose instead of a tag.
const BARE_CAVEAT_PATTERN =
  /^\s*Caveat:\s*The messages below were generated by the user while running local commands\.[^\n]*\n?/i;

export interface TranscriptText {
  /** Human-authored prompt text with all CLI scaffolding removed. */
  text: string;
  /** Invoked slash or bash command, e.g. `/model` — `null` for plain prompts. */
  command: string | null;
  /** Arguments passed alongside the command. */
  commandArgs: string;
  /** Combined stdout/stderr of a locally executed command. */
  output: string;
  /** True when at least one scaffolding block was removed. */
  stripped: boolean;
}

function includes(list: readonly string[], tag: string): boolean {
  return list.includes(tag);
}

/**
 * Splits a raw transcript message into readable prompt text and the CLI
 * scaffolding that surrounded it.
 */
export function parseTranscriptText(raw: string): TranscriptText {
  if (!raw) return { text: "", command: null, commandArgs: "", output: "", stripped: false };

  const commands: string[] = [];
  const argumentParts: string[] = [];
  const outputParts: string[] = [];
  let stripped = false;

  const remainder = raw.replace(TAG_PATTERN, (_match, rawTag: string, body: string) => {
    stripped = true;
    const tag = rawTag.toLowerCase();
    const value = body.trim();
    if (!value) return "";
    if (includes(COMMAND_TAGS, tag)) commands.push(tag === "bash-input" ? `!${value}` : value);
    else if (includes(ARGUMENT_TAGS, tag)) argumentParts.push(value);
    else if (includes(OUTPUT_TAGS, tag)) outputParts.push(value);
    return "";
  });

  const cleaned = remainder
    .replace(DANGLING_PATTERN, () => {
      stripped = true;
      return "";
    })
    .replace(ORPHAN_PATTERN, () => {
      stripped = true;
      return "";
    })
    .replace(BARE_CAVEAT_PATTERN, () => {
      stripped = true;
      return "";
    });

  return {
    text: cleaned.trim(),
    command: commands[0] ?? null,
    commandArgs: argumentParts.join(" ").trim(),
    output: outputParts.join("\n").trim(),
    stripped,
  };
}

/**
 * Reader-facing text for previews and titles: the prompt when there is one,
 * otherwise a compact representation of the command that ran.
 */
export function transcriptPlainText(raw: string): string {
  const parsed = parseTranscriptText(raw);
  if (parsed.text) return parsed.text;
  if (parsed.command) return [parsed.command, parsed.commandArgs].filter(Boolean).join(" ");
  return "";
}

/** True when a message consists solely of CLI scaffolding. */
export function isTranscriptNoise(raw: string): boolean {
  const parsed = parseTranscriptText(raw);
  return !parsed.text && !parsed.command && !parsed.output;
}

/** How a user transcript entry should appear in the chat timeline. */
export type TranscriptUserEntry =
  /** Nothing readable — the entry is dropped. */
  | { kind: "skip" }
  /** A prompt the person actually wrote. */
  | { kind: "prompt"; text: string }
  /** A slash or bash command, optionally with its output. */
  | { kind: "command"; command: string; args: string; output: string }
  /** Output belonging to the command entry that came before it. */
  | { kind: "commandOutput"; output: string };

/**
 * Decides how one user entry of a Claude Code transcript renders. Prompt text
 * always wins; entries that hold nothing but scaffolding become a command chip
 * or disappear.
 */
export function classifyTranscriptUserText(raw: string): TranscriptUserEntry {
  if (raw.trim() === "[Request interrupted by user]") return { kind: "skip" };
  const parsed = parseTranscriptText(raw);
  if (parsed.text) return { kind: "prompt", text: parsed.text };
  if (parsed.command) {
    return {
      kind: "command",
      command: parsed.command,
      args: parsed.commandArgs,
      output: parsed.output,
    };
  }
  if (parsed.output) return { kind: "commandOutput", output: parsed.output };
  return { kind: "skip" };
}
