import { describe, expect, it } from "vitest";

import {
  classifyTranscriptUserText,
  isTranscriptNoise,
  parseTranscriptText,
  transcriptPlainText,
} from "@/lib/agents/transcript-text";

describe("parseTranscriptText", () => {
  it("keeps plain prompts untouched", () => {
    const parsed = parseTranscriptText("Bitte den Branch aufräumen");
    expect(parsed).toEqual({
      text: "Bitte den Branch aufräumen",
      command: null,
      commandArgs: "",
      output: "",
      stripped: false,
    });
  });

  it("extracts a slash command instead of leaving raw markup", () => {
    const parsed = parseTranscriptText(
      "<command-name>/model</command-name>\n" +
        "<command-message>model</command-message>\n" +
        "<command-args>opus</command-args>",
    );
    expect(parsed.text).toBe("");
    expect(parsed.command).toBe("/model");
    expect(parsed.commandArgs).toBe("opus");
    expect(parsed.stripped).toBe(true);
  });

  it("collects local command output", () => {
    const parsed = parseTranscriptText(
      "<local-command-stdout>Set model to Fable 5</local-command-stdout>",
    );
    expect(parsed.output).toBe("Set model to Fable 5");
    expect(parsed.text).toBe("");
  });

  it("merges stdout and stderr in order", () => {
    const parsed = parseTranscriptText(
      "<local-command-stdout>done</local-command-stdout><local-command-stderr>warn</local-command-stderr>",
    );
    expect(parsed.output).toBe("done\nwarn");
  });

  it("drops system reminders and caveats but keeps the prompt", () => {
    const parsed = parseTranscriptText(
      "<system-reminder>Do not mention this</system-reminder>\n" +
        "Was macht der Test?\n" +
        "<local-command-caveat>Caveat: ignore me</local-command-caveat>",
    );
    expect(parsed.text).toBe("Was macht der Test?");
    expect(parsed.stripped).toBe(true);
  });

  it("drops the bare caveat sentence from older CLI releases", () => {
    const parsed = parseTranscriptText(
      "Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages.\nEchter Prompt",
    );
    expect(parsed.text).toBe("Echter Prompt");
  });

  it("renders bash mode input with its shell prefix", () => {
    const parsed = parseTranscriptText(
      "<bash-input>git status</bash-input><bash-stdout>clean</bash-stdout>",
    );
    expect(parsed.command).toBe("!git status");
    expect(parsed.output).toBe("clean");
  });

  it("removes truncated and orphaned tags", () => {
    expect(parseTranscriptText("Prompt<system-reminder>abgeschnitten").text).toBe("Prompt");
    expect(parseTranscriptText("Prompt</command-name>").text).toBe("Prompt");
  });

  it("matches scaffolding regardless of tag casing", () => {
    expect(parseTranscriptText("<SYSTEM-REMINDER>x</SYSTEM-REMINDER>Prompt").text).toBe("Prompt");
  });

  it("leaves unrelated angle brackets alone", () => {
    expect(parseTranscriptText("a < b und <div>üöä</div>").text).toBe("a < b und <div>üöä</div>");
  });

  it("ignores empty argument blocks", () => {
    const parsed = parseTranscriptText(
      "<command-name>/model</command-name><command-args></command-args>",
    );
    expect(parsed.commandArgs).toBe("");
  });
});

describe("transcriptPlainText", () => {
  it("prefers the prompt over the command", () => {
    expect(transcriptPlainText("<system-reminder>x</system-reminder>Hallo")).toBe("Hallo");
  });

  it("falls back to the command and its arguments", () => {
    expect(
      transcriptPlainText("<command-name>/review</command-name><command-args>src</command-args>"),
    ).toBe("/review src");
  });

  it("returns an empty string for pure noise", () => {
    expect(transcriptPlainText("<system-reminder>nur Rauschen</system-reminder>")).toBe("");
  });
});

describe("isTranscriptNoise", () => {
  it("detects messages that carry nothing readable", () => {
    expect(isTranscriptNoise("<system-reminder>nur Rauschen</system-reminder>")).toBe(true);
    expect(isTranscriptNoise("<command-name>/model</command-name>")).toBe(false);
    expect(isTranscriptNoise("Hallo")).toBe(false);
  });
});

describe("classifyTranscriptUserText", () => {
  it("treats human prose as a prompt", () => {
    expect(classifyTranscriptUserText("Bitte aufräumen")).toEqual({
      kind: "prompt",
      text: "Bitte aufräumen",
    });
  });

  it("keeps the prompt when scaffolding is wrapped around it", () => {
    expect(
      classifyTranscriptUserText("<system-reminder>x</system-reminder>Bitte aufräumen"),
    ).toEqual({ kind: "prompt", text: "Bitte aufräumen" });
  });

  it("turns a slash command into a command entry", () => {
    expect(
      classifyTranscriptUserText(
        "<command-name>/model</command-name><command-args>opus</command-args>",
      ),
    ).toEqual({ kind: "command", command: "/model", args: "opus", output: "" });
  });

  it("reports standalone output so it can join the previous command", () => {
    expect(
      classifyTranscriptUserText("<local-command-stdout>Set model to Fable 5</local-command-stdout>"),
    ).toEqual({ kind: "commandOutput", output: "Set model to Fable 5" });
  });

  it("keeps output attached when it arrives with the command", () => {
    expect(
      classifyTranscriptUserText(
        "<bash-input>git status</bash-input><bash-stdout>clean</bash-stdout>",
      ),
    ).toEqual({ kind: "command", command: "!git status", args: "", output: "clean" });
  });

  it("skips interruption markers and pure noise", () => {
    expect(classifyTranscriptUserText("[Request interrupted by user]")).toEqual({ kind: "skip" });
    expect(classifyTranscriptUserText("<system-reminder>x</system-reminder>")).toEqual({
      kind: "skip",
    });
    expect(classifyTranscriptUserText("")).toEqual({ kind: "skip" });
  });
});
